CREATE TABLE IF NOT EXISTS users (
users_id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
email VARCHAR(256) NOT NULL,
password VARCHAR(24) NOT NULL
);

CREATE TABLE IF NOT EXISTS address (
address_id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
house_number INTEGER(15)NOT NULL,
street VARCHAR(256) NOT NULL,
town CHAR(100) NOT NULL,
zip INT(6) NOT NULL,
users_id INTEGER NOT NULL,
FOREIGN KEY (users_id) REFERENCES users(users_id)
);

CREATE TABLE IF NOT EXISTS credit_card (
credit_card_id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
name_on_card VARCHAR(150) NOT NULL,
card_number INTEGER(16) NOT NULL,
expiration_date INT(4) NOT NULL,
ccv_number INTEGER(5) NOT NULL,
address_id INTEGER NOT NULL,
FOREIGN KEY (address_id) REFERENCES address(address_id)
);

CREATE TABLE IF NOT EXISTS orders (
orders_id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
users_id INTEGER NOT NULL,
prod_id INTEGER NOT NULL,
prod_name INTEGER NOT NULL,
FOREIGN KEY (prod_name) REFERENCES inventory(prod_name),
FOREIGN KEY (prod_id) REFERENCES inventory(prod_id),
FOREIGN KEY (users_id) REFERENCES users(users_id)
);

CREATE TABLE IF NOT EXISTS inventory(
prod_id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
prod_name VARCHAR(150),
);


