





<?php include_once('navigation.php')?>





<div = "welcome">
<h1>WELCOME TO OUR LOGIN PAGE. YOU HAVE SUCCESSFULLY LOGGED IN. WE DONT HAVE MUCH HERE YET BUT THANK YOU FOR JOINING US. HAVE A LOOK AROUND OUR PRODUCTS</H2>
<div>